[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\fpga_addon_custom_device'

[projects.cd]
path = 'Source\FPGA Addon.lvproj'

[projects.api_examples]
path = 'Source\Examples\Scripting API Examples\FPGA Addon Scripting API Examples.lvproj'

[[build.steps]]
name = 'Packed Scripting API'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Packed Scripting API'
dependency_target = 'Windows'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release PPL'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release PPL'

[[build.steps]]
name = 'Scripting Examples'
type = 'lvBuildSpec'
project = '{api_examples}'
target = 'My Computer'
build_spec = 'Scripting Examples'
dependency_target = 'Windows'

[[package]]
type = 'nipkg'
payload_dir = 'Built\FPGA Addon'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\FPGA Addon'
control_file = 'control'
package_output_dir = 'Built'

[[package]]
type = 'nipkg'
payload_dir = 'Built\Packed Scripting API'
install_destination = 'ni-paths-LV{veristand_version}DIR\vi.lib\addons\VeriStand Custom Device Scripting APIs\FPGA Addon'
control_file = 'control_scripting_api'
package_output_dir = 'Built'

[[package]]
type = 'nipkg'
payload_dir = 'Built\Scripting Examples'
install_destination = 'ni-paths-LV{veristand_version}DIR\examples\NI VeriStand Custom Devices\FPGA Addon'
control_file = 'control_scripting_examples'
package_output_dir = 'Built'
