[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\custom devices\fpga_addon'

[projects.cd]
path = 'Source\FPGA Addon Custom Device.lvproj'

[projects.api]
path = 'Source\FPGA Addon SysDef API.lvproj'

[projects.ip]
path = 'Source\FPGA Addon FPGA IP.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'

[[build.steps]]
name = 'FPGA IP'
type = 'lvBuildSpec'
project = '{ip}'
target = 'My Computer'
build_spec = 'FPGA IP Distribution'

[[build.steps]]
name = 'SysDef API'
type = 'lvBuildSpec'
project = '{api}'
target = 'My Computer'
build_spec = 'FPGA Addon System Definition API'

[package]
type = 'nipkg'
name = 'fpga-addon-custom-device-{veristand_version}'
dev_xml_path = 'Source\Custom Device FPGA Addon.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}'