[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\custom devices\fpga_addon'

[projects.cd]
path = 'Source\FPGA Addon.lvproj'

[projects.api]
path = 'Source\FPGA Addon SysDef API.lvproj'

[projects.ip]
path = 'Source\FPGA Addon FPGA IP.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpec'
project = '{cd}'
target = 'RT PXI Target - Pharlap'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Engine Libraries - Linux ARM'
type = 'lvBuildSpec'
project = '{cd}'
target = 'RT CompactRIO Target - Linux ARM'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Engine Libraries - Linux x64'
type = 'lvBuildSpec'
project = '{cd}'
target = 'RT CompactRIO Target - Linux x64'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Engine Libraries - VxWorks'
type = 'lvBuildSpec'
project = '{cd}'
target = 'RT CompactRIO Target - VxWorks'
build_spec = 'Engine Release'

[[build.steps]]
name = 'FPGA IP'
type = 'lvBuildSpec'
project = '{ip}'
target = 'My Computer'
build_spec = 'FPGA IP Distribution'

[[build.steps]]
name = 'SysDef API'
type = 'lvBuildSpec'
project = '{api}'
target = 'My Computer'
build_spec = 'System Definition API'

[package]
type = 'nipkg'
name = 'ni-fpga-addon-{veristand_version}'
dev_xml_path = 'Source\Addon\Custom Device FPGA Addon.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2019_release_branches = ["master",]